version: '3.3'

services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../test_task/.env
    ports:
      - "5432:5432"

volumes:
  postgres_data: