# Generated by Django 3.2.22 on 2023-10-06 10:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=16, verbose_name='имя')),
                ('second_name', models.CharField(max_length=35, verbose_name='фамилия')),
                ('patronymic', models.CharField(max_length=35, verbose_name='отчество')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(18, message='Минимальный возраст 18 лет!'), django.core.validators.MaxValueValidator(75, message='Максимальный возраст 75 лет!')], verbose_name='возраст')),
                ('departament', models.CharField(max_length=50, verbose_name='отдел')),
                ('post', models.CharField(max_length=50, verbose_name='должность')),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=300, verbose_name='ссылка')),
                ('time_transition', models.DateTimeField(auto_now_add=True, verbose_name='время перехода')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='сотрудник')),
            ],
        ),
    ]
